name: Test myST tutorials

on: workflow_dispatch

jobs:
  test_tutorials:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run tutorials
        run: |
          source bin/install_travis.sh
          export NB_PYTHON_PREFIX=$CONDA_PREFIX
          ./binder/postBuild
          python bin/test_tutorials.py
        env:
          WITH_MPC: yes
          WITH_MPFR: yes
          WITH_FLINT: yes
          WITH_SCIPY: yes
          BUILD_TUTORIALS: yes
          CONDA_ENV_FILE: "binder/environment.yml"
          our_install_dir: $HOME/our_usr/
